spring:
  #DATASOURCE
  jpa:
    database: MYSQL
    generate-ddl: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  #JACKSON
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      indent-output: false

#ACTUATOR
management:
  endpoints:
    web:
      exposure:
        inclsude: "*"

#LOGGING
logging-aspect:
  weave: true

logging:
  pattern:
    console: "%d [%thread] %level %logger{36} %marker - %msg%n"
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: INFO
      hibernate:
        SQL: DEBUG
    com:
      livevox: DEBUG
    root: INFO